### ISSUE TITLE
Application crashes when init an UrcaRequest

### ISSUE THREAD

**Issue by MinhNguyenVan** [mvrck-inc/urca-sdk-ios-install-guide#1]
Sorry, I'm getting a problem with Urca framework.
I integrated Urca framework (Xcode8.2.x) successfully.
But when I run Demo-Urca Objc project, it's crash when init the UrcaRequest

![screen shot 2017-06-16 at 11 38 07 am](https://user-images.githubusercontent.com/13036391/27212147-4ec5a190-5288-11e7-8ce7-7347a1539573.png)

Could you please check it?
Thanks & Best Regards !!!

**Comment by yomogi-inaba** [comment]
Hi.
Could you check the following points?

- Check Xcode version is 8.2.x (Menu bar `Xcode -> About Xcode`)
- Check `BuildSettings -> Build Options -> Always Enabled Swift Standard Libraries` is `Yes`
- Check `BuildSettings -> Build Options -> Enable Bitcode` is `Yes`

I guess that your Xcode version is 8.3.x.
Since I found same error when opening the project (`Demo-Urca-Objc.xcworkspace`) with Xcode 8.3.3.
The framework you integrated is for Xcode 8.2.1, so it should not work in other versions.

**Comment by MinhNguyenVan** [comment]
My xCode version is 8.3.3
Always Enabled Swift Standard Libraries is YES
Enable Bitcode is YES.
So I can't use this framework with xCode 8.3.3? :(

**Comment by yomogi-inaba** [comment]
Thank you for checking.

>So I can't use this framework with xCode 8.3.3? :(

Unfortunately, no.
At this moment, we are not planning to support Xcode 8.3.x or later...

**Comment by MinhNguyenVan** [comment]
はい、わかりました。
ご返事していただき、ありがとうございました。

**Comment by yomogi-inaba** [comment]
We are sorry for your inconvenience. 🙇
